### ISSUE TITLE
bert srl didn't registered 

### ISSUE THREAD

**Issue by jinruiyang** [allenai/allennlp-website#132]
when I tried 
```
        from allennlp.predictors.predictor import Predictor
        predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/srl-model-2018.05.25.tar.gz")
        predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/bert-base-srl-2019.06.17.tar.gz")
        predictor.predict(
          sentence="Did Uriah honestly think he could beat the game in under three hours?"
        )
```
on the latest version 0.8.4, but got the error:

> Traceback (most recent call last):
  File "preprocessing/srl_storyline_processing/srl_bert_test.py", line 2, in <module>
    predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/bert-base-srl-2019.06.17.tar.gz")
  File "/Users/yangjinrui/anaconda3/envs/envi2/lib/python3.7/site-packages/allennlp/predictors/predictor.py", line 144, in from_path
    return Predictor.from_archive(load_archive(archive_path), predictor_name)
  File "/Users/yangjinrui/anaconda3/envs/envi2/lib/python3.7/site-packages/allennlp/models/archival.py", line 230, in load_archive
    cuda_device=cuda_device)
  File "/Users/yangjinrui/anaconda3/envs/envi2/lib/python3.7/site-packages/allennlp/models/model.py", line 327, in load
    return cls.by_name(model_type)._load(config, serialization_dir, weights_file, cuda_device)
  File "/Users/yangjinrui/anaconda3/envs/envi2/lib/python3.7/site-packages/allennlp/common/registrable.py", line 58, in by_name
    raise ConfigurationError("%s is not a registered name for %s" % (name, cls.__name__))
allennlp.common.checks.ConfigurationError: 'srl_bert is not a registered name for Model'

**Comment by schmmd** [comment]
Closing this ticket, and apologies for the lack of response.  If you run into more issues with AllenNLP, please cut them on https://github.com/allenai/allennlp, which we monitor regularly.
